### PR TITLE
Indexer address validation

### LINKED ISSUE #78: Stricter validation for INDEXER_ADDRESS
Off the back of https://github.com/graphops/subgraph-radio/issues/62 , we should implement stricter checks for the `INDEXER_ADDRESS` variable. The Radio should fail to start if the provided `PRIVATE_KEY`/`MNEMONIC` doesn't resolve to the provided `INDEXER_ADDRESS`, using either the Graphcast Registry or the Network Subgraph. 

Before that check, we should do a minimal check to see if the provided `INDEXER_ADDRESS` is saved by the Radio as a valid eth address, because in some cases (for instance missing quotes in a `.yml` file config) the address format can be malformed.

### PR DESCRIPTION
**Pull request by cargopete**
- [x] `INDEXER_ADDRESS` checked for being a valid eth address
- [x] `INDEXER_ADDRESS` checked against graphcast registry and network subgraph, also making sure that provided `MNEMONIC`/`PRIVATE_KEY` is actually tied to the provided `INDEXER_ADDRESS`

Resolves https://github.com/graphops/subgraph-radio/issues/78

### CODE REVIEW

File: subgraph-radio/src/config.rs [hunk 1]
```diff
@@ -67,11 +68,50 @@ impl Config {
         };
 
         std::env::set_var("RUST_LOG", config.radio_setup().log_level.clone());
+        config.validate_indexer_address().await;
```
Comment (hopeyen) [inline subgraph-radio/src/config.rs]: most async validation (valid graph node, network subgraph, indexer management), are done when creating a RadioOperator (https://github.com/graphops/subgraph-radio/blob/16e6892f33dcaf9508a07a25f71488c65531d17b/subgraph-radio/src/operator/mod.rs#L68). 

I think It should be sufficient to just have is_valid_eth_addr as part of the value parser, such that `args` don't need changes. Instead do validation indexer address with other async validations. 

It is fine if you prefer to add everything to `args`, just would be good to have external validations of config should be done consistently in one place when it can be

File: subgraph-radio/src/config.rs [hunk 2]
```diff
@@ -67,11 +68,50 @@ impl Config {
...
+            .await;
+
+        if let Ok(registered_acc) = registered_address {
+            if registered_acc == account {
+                return;
+            }
+        }
+
+        let matched_account = account
+            .account_from_network(self.graph_stack().network_subgraph())
```
Comment (hopeyen) [inline subgraph-radio/src/config.rs]: `account_from_network` checks for a valid graph account instead of valid indexer

File: subgraph-radio/src/config.rs [hunk 3]
```diff
@@ -67,11 +68,50 @@ impl Config {
...
+
+        let account = Account::new(
+            agent.to_ascii_lowercase(),
+            self.graph_stack()
+                .indexer_address()
+                .to_string()
+                .to_ascii_lowercase(),
+        );
+
+        let registered_address = account
```
Comment (hopeyen) [inline subgraph-radio/src/config.rs]: Have you considered using `Account.verify(...)`?

File: subgraph-radio/src/config.rs [hunk 4]
```diff
@@ -52,7 +53,7 @@ pub struct Config {
 }
 
 impl Config {
-    /// Parse config arguments
+    /// Validate and config arguments
```
Comment (hopeyen) [inline subgraph-radio/src/config.rs]: the comment looks off

File: subgraph-radio/src/config.rs [hunk 5]
```diff
@@ -81,6 +112,22 @@ impl Config {
         Ok(String::from(value))
     }
 
+    fn is_valid_ethereum_address(address: &str) -> bool {
```
Comment (hopeyen) [inline subgraph-radio/src/config.rs]: maybe consider moving `is_valid_ethereum_address` and `parse_indexer_address` out of Config impl so that they are standalone helpers. They don't access Config fields and would be easier to refactor when it's time to move these helpers to the sdk

**Review by hopeyen — COMMENTED** [review]
very very close

**Review by hopeyen — DISMISSED** [review]
looks good, please rebase to dev or wait til #117 is merged

**Review by hopeyen — APPROVED** [review]
coolio
